# Copyright (c) 2024 Jiaqi Liu
---
name: CI/CD

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  deploy-documentation:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: "./yarn.lock"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build documentation
        run: yarn build
      - name: Load CNAME
        run: cp CNAME build
      - name: Deploy to GitHub Pages
        # if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: QubitPi
          user_email: jack20220723@gmail.com
